### ISSUE TITLE
Add an easy way to host locally to work around CORS policy

### ISSUE THREAD

**Issue by AnimiVulpis** [Sankeyfactory/sankeyfactory.github.io#2]
After building locally and trying to run it via opening the `dist/index.html` in chrome the following problem is reported on the js console:
```
Access to script at 'file:///redacted/path/sankeyfactory.github.io/dist/script.js' from origin 'null' has been blocked by CORS policy:
Cross origin requests are only supported for protocol schemes:
chrome, chrome-extension, chrome-untrusted, data, http, https, isolated-app.
```

I'll open a PR in a moment that uses docker to provide an easy way to host the tool locally (e.g. for development).
I know there are other ways to do this, but many developers nowadays have docker installed already.

**Comment by andev0** [comment]
Won't just adding `--servedir=dist` to esbuild do the thing without Docker?
E.g. `npx esbuild src/main.ts --bundle --outfile=dist/script.js --servedir=dist`

**Comment by AnimiVulpis** [comment]
Jepp. I didn't know about `servedir` until now^^.

As `esbuild` is already a build dependency the docker _route_ is pretty unnecessary for local development.

I'll modify the PR bases on this: [esbuild Live reload](https://esbuild.github.io/api/#live-reload)

Thanks for the suggestion

**Comment by AnimiVulpis** [comment]
Will use `esbuild` built-in solution for serving content based on the above [comment](https://github.com/Sankeyfactory/sankeyfactory.github.io/issues/2#issuecomment-2328075445)

**Comment by AnimiVulpis** [comment]
I meant to close the PR (because you can't rename the branch of an open PR) not the issue 🙄
