### ISSUE TITLE
Scrollbars are not styled nicely

### ISSUE THREAD

**Issue by AnimiVulpis** [Sankeyfactory/sankeyfactory.github.io#5]
More an observation than a problem.
If the scrollbars are visible on e.g. MacOS (For example by setting "Show scroll bars" to "Always") those are a bit ugly.

I'll provide a PR that at least changes the scrollbar colors to make it visually more appealing.

Maybe later I'll think about how to improve the situation for users that have scrollbars always visible.

**Comment by andev0** [comment]
Fixed by https://github.com/Sankeyfactory/sankeyfactory.github.io/commit/eb3c66fedc10be14c2bbf17986463a5bcc8118ca and https://github.com/Sankeyfactory/sankeyfactory.github.io/commit/943759697fce534ac0b62d869046bcf226656e67
